### ISSUE TITLE
LibAsynql too outdated.

### ISSUE THREAD

**Issue by TacoError** [Cosmoverse/FloatingText#9]
The LibAsynql version given in the poggit.yml causes issues on the latest version of pm 4.0 and in pm5

Error

```
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of cosmicpe\floatingtext\libs\poggit\libasynql\generic\GenericStatementImpl::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementImpl.php:233
Stack trace:
#0 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementImpl.php(41): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar://C:/Users...', 233)
#1 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar://C:/Users...')
#2 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('cosmicpe\\floati...')
#3 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementFileParser.php(220): BaseClassLoader->{closure}('cosmicpe\\floati...')
#4 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementFileParser.php(151): cosmicpe\floatingtext\libs\poggit\libasynql\generic\GenericStatementFileParser->endCommand()
#5 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementFileParser.php(110): cosmicpe\floatingtext\libs\poggit\libasynql\generic\GenericStatementFileParser->tryCommand('}')
#6 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementFileParser.php(85): cosmicpe\floatingtext\libs\poggit\libasynql\generic\GenericStatementFileParser->readLine(13, '-- #  }')
#7 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/base/DataConnectorImpl.php(108): cosmicpe\floatingtext\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
#8 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/libasynql.php(151): cosmicpe\floatingtext\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(Resource id #1675)
#9 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/db/Database.php(25): cosmicpe\floatingtext\libs\poggit\libasynql\libasynql::create(Object(cosmicpe\floatingtext\Loader), Array, Array)
#10 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/Loader.php(26): cosmicpe\floatingtext\db\Database->__construct(Object(cosmicpe\floatingtext\Loader))
#11 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/src/plugin/PluginBase.php(118): cosmicpe\floatingtext\Loader->onEnable()
#12 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/src/plugin/PluginManager.php(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#13 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/src/Server.php(1395): pocketmine\plugin\PluginManager->enablePlugin(Object(cosmicpe\floatingtext\Loader))
#14 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/src/Server.php(1030): pocketmine\Server->enablePlugins(Object(pocketmine\plugin\PluginEnableOrder))
#15 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/src/PocketMine.php(339): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), 'C:\\Users\\radlt\\...', 'C:\\Users\\radlt\\...')
#16 phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/PocketMine-MP.phar/src/PocketMine.php(362): pocketmine\server()
#17 C:\Users\radlt\OneDrive\Desktop\pocketmine-5.0-phar - Copy - Copy\PocketMine-MP.phar(11): require('phar://C:/Users...')
#18 {main} in phar://C:/Users/radlt/OneDrive/Desktop/pocketmine-5.0-phar - Copy - Copy/plugins/FloatingText_dev-36.phar/src/cosmicpe/floatingtext/libs/poggit/libasynql/generic/GenericStatementImpl.php on line 41
```

**Comment by Muqsit** [comment]
This crash is made redundant by https://github.com/Cosmoverse/FloatingText/commit/d6e6b63ac90e6ba337881a3026eb15a89a32405c which adds PM5 support 👍
